export const CRON_AVATAR_CLEANUP_SCHEDULE =
  process.env.CRON_AVATAR_CLEANUP_SCHEDULE ?? '0 3 * * *';
export const CRON_WEBHOOK_EVENT_CLEANUP_SCHEDULE =
  process.env.CRON_WEBHOOK_EVENT_CLEANUP_SCHEDULE ?? '30 3 * * *';

export const CRON_WEBHOOK_EVENT_RETENTION_DAYS = Number(
  process.env.CRON_WEBHOOK_EVENT_RETENTION_DAYS ?? 30,
);

export const AVATAR_CLEANUP_GRACE_PERIOD_MS = 10 * 60 * 1000;
