import type { Metadata } from "next";
import { Newsreader, Geist, Geist_Mono } from 'next/font/google';
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { SmoothScroll } from "@/components/layout/SmoothScroll";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});
const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-mono' });

const newsreader = Newsreader({
  subsets: ['latin'],
  variable: '--font-newsreader',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("bg-bg", "text-ink", "h-full", "antialiased", newsreader.variable, "font-sans", geist.variable, geistMono.variable)}
    >
      {/* No flex/min-h here: ScrollSmoother fixes #smooth-wrapper and drives
          the body's height itself, so a flex column on the body would have
          nothing in flow to lay out. The Navbar stays a sibling of the wrapper
          because it's `fixed` — inside, it would ride the smoothed transform. */}
      <body>
        <Navbar />
        {/* Footer lives inside SmoothScroll, not beside it like Navbar — it's
            normal in-flow content meant to scroll with the page (every route,
            not just the landing page), not a fixed element riding above the
            smoothed transform. */}
        <SmoothScroll>
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
