import type { Metadata } from 'next';
import { Newsreader, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Navbar } from '@/components/layout/Navbar';
import { SmoothScroll } from '@/components/layout/SmoothScroll';
import { SessionBootstrap } from '@/components/auth/SessionBootstrap';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });
const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-mono' });

const newsreader = Newsreader({
  subsets: ['latin'],
  variable: '--font-newsreader',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'bg-bg',
        'text-ink',
        'h-full',
        'antialiased',
        newsreader.variable,
        'font-sans',
        geist.variable,
        geistMono.variable,
      )}
    >
      {/* No flex/min-h here: ScrollSmoother fixes #smooth-wrapper and drives
          the body's height itself, so a flex column on the body would have
          nothing in flow to lay out. The Navbar stays a sibling of the wrapper
          because it's `fixed` — inside, it would ride the smoothed transform. */}
      <body>
        <SessionBootstrap />
        <Navbar />
        {/* Footer is NOT rendered here — it's opted into per-route (currently
            just the landing page's own composition) rather than mounted
            globally. It was here originally, but a footer below a
            `min-h-screen`-centered single-purpose screen (auth, and any
            future ones like it) pushes the page's total height past one
            viewport, throwing off that screen's own vertical centering
            relative to what's actually visible without scrolling. */}
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
